site_name: Template example for simple doc generation 

theme: readthedocs

docs_dir: docs/sources

pages:
- Home: index.md
- my_module_1:
  - Introduction: my_module_1/index.md
  - Some Functions: my_module_1/some_functions.md
  - Some Classes: my_module_1/some_classes.md
- my_module_2:
  - Introduction: my_module_2/index.md
  - All Functions Module: my_module_2/all_functions_module.md
  - All Classes Module: my_module_2/all_classes_module.md
